
# Makefile for osd and tv 
obj-$(CONFIG_AM_TV_OUTPUT)	+= vout/
obj-$(CONFIG_AM_TCON_OUTPUT)+= vout/
obj-$(CONFIG_AM_GE2D)	+= ge2d/
obj-$(CONFIG_FB_AM)	+= osd/

obj-y	+= aml_logo/
obj-$(CONFIG_AMLOGIC_BACKLIGHT)	+= backlight/



