#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SINTEK_CAPACITIVE_TOUCHSCREEN)		+= stkxxx.o
obj-$(CONFIG_ITK_CAPACITIVE_TOUCHSCREEN)		+= itk.o
obj-$(CONFIG_EETI_CAPACITIVE_TOUCHSCREEN)		+= eeti.o
obj-$(CONFIG_SIS92XX_CAPACITIVE_TOUCHSCREEN) += capts.o sis92xx.o
obj-$(CONFIG_HX8520_CAPACITIVE_TOUCHSCREEN) += capts.o hx8520.o
obj-$(CONFIG_RAYDIUM_CAPACITIVE_TOUCHSCREEN) += capts.o raydium.o
obj-$(CONFIG_GOODIX_CAPACITIVE_TOUCHSCREEN) += goodix_touch.o
obj-$(CONFIG_UOR7X5X_RESISTIVE_TOUCHSCREEN) += uor7x5x.o
obj-$(CONFIG_UOR6X5X_RESISTIVE_TOUCHSCREEN) += uor6x5x.o
obj-$(CONFIG_PIXCIR_CAPACITIVE_TOUCHSCREEN) += pixcir_i2c_ts.o
obj-$(CONFIG_SITRONIX_CAPACITIVE_TOUCHSCREEN) += capts.o  sitronix_st15xx_ts.o
obj-$(CONFIG_FOCALTECH_CAPACITIVE_TOUCHSCREEN) += capts.o focaltech_5x06.o