#                             
# Makefile for eFuse.         
#                             
                              
obj-$(CONFIG_EFUSE) += efuse.o
                              
                              