
# Makefile for osd and tv 

audiodsp-objs=	audiodsp_module.o \
				dsp_control.o 		\
				dsp_microcode.o 	\
				dsp_mailbox.o			\
				dsp_monitor.o			\
				dsp_codec.o


obj-$(CONFIG_AML_AUDIO_DSP)    +=audiodsp.o

