obj-$(CONFIG_AML_HDMI_TX)		+= hdmitx.o


hdmitx-objs := hdmi_tx.o hdmi_tx_video.o hdmi_tx_audio.o hdmi_tx_edid.o hdmi_tx_audio.o \
                m1/hdmi_tx_reg.o m1/hdmi_tx_hw.o


EXTRA_CFLAGS += -O0


