#
# Makefile for the amlogic platform camera interface device drivers.
#
EXTRA_AFLAGS=-mfloat-abi=softfp -mfpu=neon
amlvideodri-objs := amlvideo.o
amlvm-objs := common/vfutil.o

obj-y +=common/vfutil.o
obj-y +=amlvideodri.o 
#obj-$(CONFIG_AMLOGIC_VIDEOIN_MANAGER)  += amlvm.o
